"""
ForgeAI Backend — Pipeline Code Generator
Owner: Member 2 (Backend Engineer)

Generates a clean, runnable preprocessing_pipeline.py from the
approved action list. No AI code — only pre-written templates.
"""

from datetime import datetime


# ─────────────────────────────────────────────────────────────
# Code line templates per action type
# ─────────────────────────────────────────────────────────────

def _code_for_action(action: dict) -> list[str]:
    """Return the Python source lines for a single approved action."""
    action_type = action.get("type", "").lower()
    col = action.get("column", "")
    action_label = action.get("action", "").lower()
    lines: list[str] = []

    if action_type == "dedup":
        lines.append("    df = df.drop_duplicates().reset_index(drop=True)")

    elif action_type == "drop":
        lines.append(f"    df = df.drop(columns=['{col}'], errors='ignore')")

    elif action_type == "impute":
        if "median" in action_label:
            lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].median())")
        elif "mean" in action_label:
            lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].mean())")
        elif "mode" in action_label:
            lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].mode()[0])")
        else:
            lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].median())")

    elif action_type == "transform":
        if "log" in action_label:
            lines.append(f"    df['{col}'] = np.log1p(df['{col}'].clip(lower=0))")

    elif action_type == "encode":
        if "one-hot" in action_label or "onehot" in action_label:
            lines.append(
                f"    df = pd.get_dummies(df, columns=['{col}'], drop_first=True, dtype=int)"
            )
        else:  # ordinal / label
            mapping = action.get("ordinal_mapping")
            if mapping:
                lines.append(f"    _order = {repr(mapping)}")
                lines.append(f"    df['{col}'] = df['{col}'].map(_order)")
            else:
                lines.append(f"    _vals = sorted(df['{col}'].dropna().unique())")
                lines.append(
                    f"    df['{col}'] = df['{col}'].map({{v: i for i, v in enumerate(_vals)}})"
                )

    elif action_type == "outlier":
        lines.append(f"    _q1 = df['{col}'].quantile(0.05)")
        lines.append(f"    _q3 = df['{col}'].quantile(0.95)")
        lines.append(f"    df['{col}'] = df['{col}'].clip(_q1, _q3)")

    elif action_type == "scale":
        lines.append(f"    _scaler = StandardScaler()")
        lines.append(f"    df[['{col}']] = _scaler.fit_transform(df[['{col}']])")

    return lines


# ─────────────────────────────────────────────────────────────
# Public generator
# ─────────────────────────────────────────────────────────────

def generate_pipeline_code(actions: list[dict], dataset_name: str) -> str:
    """
    Generate a runnable preprocessing_pipeline.py string from the
    approved action list.
    """
    stem = dataset_name.replace(".csv", "").replace(" ", "_").lower()
    today = datetime.now().strftime("%B %d, %Y")

    lines: list[str] = [
        "# ForgeAI — Generated Preprocessing Pipeline",
        f"# Dataset: {dataset_name}",
        f"# Generated: {today}",
        "#",
        "# This file was automatically generated by ForgeAI.",
        "# Every step corresponds to an AI decision approved by you.",
        "",
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.preprocessing import StandardScaler",
        "",
        "",
        "def preprocess(df: pd.DataFrame) -> pd.DataFrame:",
        '    """Apply the ForgeAI-approved preprocessing pipeline."""',
        "    df = df.copy()",
        "",
    ]

    for i, action in enumerate(actions, start=1):
        col = action.get("column", "Dataset")
        reason = action.get("reason", "")[:80]
        lines.append(f"    # Step {i}: {action.get('action', '')} — {col}")
        if reason:
            lines.append(f"    # Reason: {reason}{'...' if len(action.get('reason','')) > 80 else ''}")

        code_lines = _code_for_action(action)
        if code_lines:
            lines.extend(code_lines)
        else:
            lines.append(f"    # (no handler for type '{action.get('type')}')")
        lines.append("")

    lines += [
        "    return df",
        "",
        "",
        'if __name__ == "__main__":',
        f'    raw = pd.read_csv("{stem}.csv")',
        "    clean = preprocess(raw)",
        f'    clean.to_csv("{stem}_clean.csv", index=False)',
        '    print(f"Saved: {len(clean)} rows × {len(clean.columns)} columns")',
        "",
    ]

    return "\n".join(lines)
