import json


class PromptBuilder:

    def __init__(self):
        pass

    def build_system_prompt(self):
        return """
You are ForgeAI.

ForgeAI is an expert AI Data Engineer and Machine Learning Engineer.

Your job is to analyze dataset profiles and recommend the BEST preprocessing strategy.

You NEVER write Python code.

You NEVER invent dataset statistics.

You NEVER invent columns.

The dataset profile was generated by deterministic Python code and is always correct.

You must produce reliable preprocessing recommendations.

Always prioritize correctness over creativity.

Return ONLY valid JSON.

Do NOT use markdown.

Do NOT explain outside JSON.

Every recommendation MUST contain a reason.

Every recommendation MUST contain a confidence score between 0 and 100.
"""

    def build_dataset_context(self, profile):

        lines = []

        dataset = profile["dataset"]

        lines.append("DATASET SUMMARY")
        lines.append("=" * 40)
        lines.append(f"Rows: {dataset['rows']}")
        lines.append(f"Columns: {dataset['columns']}")
        lines.append(f"Duplicate Rows: {dataset['duplicate_rows']}")
        lines.append(f"Health Score: {dataset['health_score']}")
        lines.append("")

        lines.append("COLUMN PROFILES")
        lines.append("=" * 40)

        for column in profile["columns"]:

            lines.append(f"Column: {column['name']}")
            lines.append(f"Type: {column['semantic_type']}")
            lines.append(f"Dtype: {column['dtype']}")
            lines.append(f"Missing: {column['missing_percent']}%")
            lines.append(f"Risk: {column['risk']}")
            lines.append(f"Unique Values: {column['unique_values']}")
            lines.append(f"Constant: {column['constant']}")
            lines.append(f"Identifier: {column['possible_identifier']}")

            if column["semantic_type"] == "numeric":

                lines.append(f"Mean: {column['mean']}")
                lines.append(f"Median: {column['median']}")
                lines.append(f"Std: {column['std']}")
                lines.append(f"Skewness: {column['skewness']}")
                lines.append(f"Outliers: {column['outlier_count']}")

            elif column["semantic_type"] in ["categorical", "text"]:

                lines.append(
                    f"Top Values: {column['top_values']}"
                )

            lines.append("-" * 40)

        return "\n".join(lines)

    def build_output_schema(self):

        return """
Return EXACTLY this JSON structure.

{
    "preprocessing_steps": [
        {
            "column": "",
            "issue": "",
            "action": "",
            "reason": "",
            "confidence": 0
        }
    ],

    "identifier_columns": [],

    "target_column": null,

    "encoding": {},

    "scaling": {},

    "duplicates": "",

    "recommendations": "",

    "dataset_health_score": 0,

    "summary": ""
}
"""

    def build_prompt(self, profile):

        system_prompt = self.build_system_prompt()

        dataset_context = self.build_dataset_context(profile)

        output_schema = self.build_output_schema()

        return f"""
{system_prompt}

====================================================

TASK

Analyze the dataset profile below.

Recommend the best preprocessing pipeline.

Only recommend actions that are justified.

Never recommend unnecessary preprocessing.

====================================================

{dataset_context}

====================================================

{output_schema}
"""


if __name__ == "__main__":

    from config import DATASETS_DIR

    with open(DATASETS_DIR / "profile.json", "r", encoding="utf-8") as f:
        profile = json.load(f)

    builder = PromptBuilder()

    print(builder.build_prompt(profile))